<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jairon Ojeda S.">

<title>Coeficiente de Correlación de los Rangos de Spearman – Jairon K. Ojeda S.</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../favicon.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Sin resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>

<link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

<link href="https://fonts.googleapis.com/css?family=Fira+Sans|Merriweather" rel="stylesheet">

<script src="https://kit.fontawesome.com/0fba9333d8.js" crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">


  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Jairon K. Ojeda S.</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Buscar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Navegación de palanca" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../blog/index.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../publications/index.html"> 
<span class="menu-text">Publicaciones</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../software/index.html"> 
<span class="menu-text">Shiny apps</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../portafolio/index.html"> 
<span class="menu-text">Portafolio</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../servicios/index.html"> 
<span class="menu-text">Servicios</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta página</h2>
   
  <ul>
  <li><a href="#qué-es-la-correlación-de-spearman" id="toc-qué-es-la-correlación-de-spearman" class="nav-link active" data-scroll-target="#qué-es-la-correlación-de-spearman">¿Qué es la correlación de Spearman?</a></li>
  <li><a href="#expresión-matemática" id="toc-expresión-matemática" class="nav-link" data-scroll-target="#expresión-matemática">Expresión Matemática</a></li>
  <li><a href="#comprobaciones-en-r" id="toc-comprobaciones-en-r" class="nav-link" data-scroll-target="#comprobaciones-en-r">Comprobaciones en R</a>
  <ul class="collapse">
  <li><a href="#ejemplo-sin-empates" id="toc-ejemplo-sin-empates" class="nav-link" data-scroll-target="#ejemplo-sin-empates">1. Ejemplo sin empates</a></li>
  <li><a href="#ejemplo-con-empates-rangos-promediados" id="toc-ejemplo-con-empates-rangos-promediados" class="nav-link" data-scroll-target="#ejemplo-con-empates-rangos-promediados">2. Ejemplo con empates (Rangos promediados)</a></li>
  </ul></li>
  <li><a href="#que-es-una-relación-monotónica-o-tambien-llamado-asociación-monotónica" id="toc-que-es-una-relación-monotónica-o-tambien-llamado-asociación-monotónica" class="nav-link" data-scroll-target="#que-es-una-relación-monotónica-o-tambien-llamado-asociación-monotónica">¿Que es una relación monotónica o tambien llamado asociación monotónica?</a>
  <ul class="collapse">
  <li><a href="#asociación-monótona-spearman-alto-pearson" id="toc-asociación-monótona-spearman-alto-pearson" class="nav-link" data-scroll-target="#asociación-monótona-spearman-alto-pearson">Asociación monótona (Spearman ≈ alto, Pearson ↓)</a></li>
  </ul></li>
  <li><a href="#supuestos-del-coeficiente-de-spearman-rho" id="toc-supuestos-del-coeficiente-de-spearman-rho" class="nav-link" data-scroll-target="#supuestos-del-coeficiente-de-spearman-rho">Supuestos del coeficiente de Spearman (<span class="math inline">\rho</span>)</a></li>
  <li><a href="#interpretación-de-rho-de-spearman" id="toc-interpretación-de-rho-de-spearman" class="nav-link" data-scroll-target="#interpretación-de-rho-de-spearman">Interpretación de <span class="math inline">\rho</span> de Spearman</a>
  <ul class="collapse">
  <li><a href="#rango-de-valores" id="toc-rango-de-valores" class="nav-link" data-scroll-target="#rango-de-valores">Rango de valores</a></li>
  <li><a href="#fuerza-de-la-relación" id="toc-fuerza-de-la-relación" class="nav-link" data-scroll-target="#fuerza-de-la-relación">Fuerza de la relación</a></li>
  </ul></li>
  <li><a href="#ejemplos-practicos-usando-r" id="toc-ejemplos-practicos-usando-r" class="nav-link" data-scroll-target="#ejemplos-practicos-usando-r">Ejemplos practicos usando R</a></li>
  <li><a href="#bibliografia-recomendada" id="toc-bibliografia-recomendada" class="nav-link" data-scroll-target="#bibliografia-recomendada">Bibliografia Recomendada</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Coeficiente de Correlación de los Rangos de Spearman</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Correlación</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor/a</div>
    <div class="quarto-title-meta-contents">
             <p>Jairon Ojeda S. </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">15 septiembre 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="qué-es-la-correlación-de-spearman" class="level2">
<h2 class="anchored" data-anchor-id="qué-es-la-correlación-de-spearman">¿Qué es la correlación de Spearman?</h2>
<p>En muchos análisis estadísticos se suele comenzar evaluando la asociación entre dos variables mediante el coeficiente de correlación de Pearson, el cual es apropiado cuando la relación entre ellas es esencialmente lineal. Sin embargo, en la práctica no siempre las variables se comportan siguiendo un patrón estrictamente lineal, pues es común encontrar conjuntos de datos en los que existe algún tipo de asociación, pero cuya forma no obedece a una tendencia lineal definida; en tales casos, el coeficiente de Pearson puede ofrecer resultados poco representativos o incluso engañosos.</p>
<p>Para atender adecuadamente estas situaciones, se recurre al <strong>coeficiente de correlación de rangos de Spearman,</strong> también llamado simplemente correlación de Spearman. Este es un método no paramétrico que evalúa la asociación transformando los valores originales en rangos, de modo que el análisis se centra en el orden relativo de los datos y no en su magnitud absoluta. El coeficiente se representa como <span class="math inline">\rho</span> (rho) y cuantifica la fuerza y dirección de una <strong>relación monotónica</strong> entre las variables, diferenciándose así de Pearson, cuyo enfoque se limita a relaciones lineales.</p>
<p>Esta característica convierte a Spearman en una alternativa más robusta cuando los datos presentan relaciones no lineales, distribuciones no normales o valores atípicos (no asume homocedasticidad) que pueden distorsionar sustancialmente la correlación de Pearson. En términos conceptuales, puede entenderse a Spearman como una aplicación del coeficiente de Pearson, pero calculado sobre valores ordenados o jerarquizados, razón por la cual comparte varios de sus principios matemáticos, aunque con ventajas claras en contextos no paramétricos.</p>
</section>
<section id="expresión-matemática" class="level2">
<h2 class="anchored" data-anchor-id="expresión-matemática">Expresión Matemática</h2>
<p>Cuando los datos no contienen empates, <span class="math inline">\rho</span> se puede hallar calculando la diferencia de los valores ordenados mediante la siguiente ecuación:</p>
<p><span id="eq-cor1"><span class="math display">
r_s = 1-\frac{6 \sum d_i^2}{n(n^2 - 1)}
\tag{1}</span></span></p>
<p>Donde <span class="math inline">d_i</span> es la diferencia de las variables ordenadas y <span class="math inline">n</span> es el número de muestras. Cuando el conjunto de datos contiene empates, la fórmula anterior arrojará valores incorrectos o sesgados. Cuando los datos contienen empates, el coeficiente de Spearman, se calculan <strong>sobre los rangos</strong> de las variables. Así, la correlación se expresa como:</p>
<p><span class="math display">
r_s = \frac{\sum_{i} (rg_{x_i} - \overline{rg_x})(rg_{y_i} - \overline{rg_y})}
           {\sqrt{\sum_{i} (rg_{x_i} - \overline{rg_x})^2 \; \sum_{i} (rg_{y_i} - \overline{rg_y})^2}}
</span></p>
<p>Lo cual es equivalente a su forma basada en covarianza entre rangos:</p>
<p><span id="eq-cor2"><span class="math display">
r_s = \rho_{rg_x, rg_y} = \frac{cov(rg_x, rg_y)}{\sigma_{rg_x} \sigma_{rg_y}}
\tag{2}</span></span></p>
<p>donde:</p>
<p><span class="math display">
\text{cov}(rg_x, rg_y) = \frac{1}{n} \sum_{i} (rg_{x_i} - \overline{rg_x})(rg_{y_i} - \overline{rg_y})
</span></p>
<p>y las desviaciones estándar también corresponden a los <strong>rangos</strong>:</p>
<p><span class="math display">
\sigma_{rg_x} = \sqrt{\frac{1}{n} \sum_{i} (rg_{x_i} - \overline{rg_x})^2}
</span></p>
<p>donde <span class="math inline">\rho</span> denota el coeficiente de Pearson usual, pero sobre las variables ordenadas.<span class="math inline">cov(rg_x, rg_y)</span> es la covarianza y <span class="math inline">\sigma_{rg_x}, \sigma_{rg_y}</span> son las desviaciones estándar de las variables ordenadas.</p>
<blockquote class="blockquote">
<p>A groso modo cuando no hay empates en las observaciones, se usa la formula corta (<a href="#eq-cor1" class="quarto-xref">Ecuación&nbsp;1</a>) o tambien Pearson pero sobre los rangos, <span class="math inline">rg_x, rg_y</span>, pero cuando hay empates, ahi ya no se usa la formula corta, solo pearson sobre los rangos (<a href="#eq-cor2" class="quarto-xref">Ecuación&nbsp;2</a>).En general el coeficiente de Spearman es exactamente la correlación de Pearson pero aplicada a los rangos (ranks) de los datos.</p>
</blockquote>
<p>La hipótesis nula para este coeficiente es:</p>
<p><span class="math inline">H_0 : \rho = 0</span></p>
<p>que se puede comprobar mediante el estadístico <em>t</em> con la siguiente fórmula:</p>
<p><span class="math display">
t = \frac{r_s}{\sqrt{\frac{1-r_s^2}{n-2}}}
</span> Esta prueba se basa en la aproximación de Pearson aplicada a rangos donde:</p>
<ul>
<li><span class="math inline">t</span> es el valor calculado para la prueba de significancia del coeficiente de correlación de Spearman.<br>
</li>
<li><span class="math inline">r_s</span> es el coeficiente de correlación de Spearman.<br>
</li>
<li><span class="math inline">n</span> es el tamaño de la muestra.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p>La asociación monótona indica que las variables tienden a moverse en la misma dirección relativa, pero no necesariamente a un ritmo constante. Es importante destacar que todas las correlaciones lineales son monótonas, pero no todas las asociaciones monótonas son lineales, ya que también puede haber asociaciones monótonas no lineales.</p>
<p>Por otro lado Un valor alto o bajo de <span class="math inline">\rho</span> indica <strong>asociación entre variables</strong>, pero no implica que una variable cause cambios en la otra (<strong>correlación no implica causalidad</strong>). La inferencia causal requiere diseño experimental o métodos adicionales de análisis.</p>
</div>
</div>
</section>
<section id="comprobaciones-en-r" class="level2">
<h2 class="anchored" data-anchor-id="comprobaciones-en-r">Comprobaciones en R</h2>
<p>Para fines académicos se presentan ejemplos sintéticos para corroborar como funcionan ambas formulas usando la función <code>cor()</code> aplicando Spearman directamente y Pearson sobre los rangos, con el objetivo de corroborar lo mencionado anteriormente tanto para empates y sin empates.</p>
<section id="ejemplo-sin-empates" class="level3">
<h3 class="anchored" data-anchor-id="ejemplo-sin-empates">1. Ejemplo sin empates</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">20</span>, <span class="dv">30</span>, <span class="dv">40</span>, <span class="dv">50</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">7</span>, <span class="dv">9</span>, <span class="dv">12</span>, <span class="dv">15</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Rangos</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>rg_x <span class="ot">&lt;-</span> <span class="fu">rank</span>(x)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>rg_y <span class="ot">&lt;-</span> <span class="fu">rank</span>(y)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>rg_x; rg_y</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1 2 3 4 5</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1 2 3 4 5</code></pre>
</div>
</div>
<p>Se obtienen los rangos a los cuales se les aplicara el coeficiente de pearson.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Spearman manual (Pearson sobre rangos)</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>rs_manual <span class="ot">&lt;-</span> <span class="fu">cor</span>(rg_x, rg_y, <span class="at">method =</span> <span class="st">"pearson"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>rs_manual</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<p>se observa que al aplicar pearson a los rangos se tiene un valor de <strong>1</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Spearman automático</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>rs_cor <span class="ot">&lt;-</span> <span class="fu">cor</span>(x, y, <span class="at">method =</span> <span class="st">"spearman"</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>rs_cor</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<p>Ahora al aplicarse la función de Spearman directamente, se obtiene el mismo valor <strong>1</strong></p>
<p>Al no existir empates y al ser la relación perfectamente monótona creciente, el coeficiente de Spearman es exactamente 1, tanto al aplicar la fórmula manual en R (Pearson sobre los rangos) como al usar la función directa de R. Ambos métodos son equivalentes en ausencia de empates.</p>
</section>
<section id="ejemplo-con-empates-rangos-promediados" class="level3">
<h3 class="anchored" data-anchor-id="ejemplo-con-empates-rangos-promediados">2. Ejemplo con empates (Rangos promediados)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">10</span>, <span class="dv">20</span>, <span class="dv">30</span>, <span class="dv">30</span>, <span class="dv">30</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">6</span>, <span class="dv">9</span>, <span class="dv">9</span>, <span class="dv">12</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Rangos con empates</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>rg_x <span class="ot">&lt;-</span> <span class="fu">rank</span>(x, <span class="at">ties.method =</span> <span class="st">"average"</span>)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>rg_y <span class="ot">&lt;-</span> <span class="fu">rank</span>(y, <span class="at">ties.method =</span> <span class="st">"average"</span>)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>rg_x; rg_y</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.5 1.5 3.0 5.0 5.0 5.0</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.0 2.5 2.5 4.5 4.5 6.0</code></pre>
</div>
</div>
<p>Se obtienen los rangos para el caso de empates promediando con <code>ties.method = "average"</code> a los cuales se les aplicara el coeficiente de pearson.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Spearman manual con Pearson sobre rangos</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>rs_manual <span class="ot">&lt;-</span> <span class="fu">cor</span>(rg_x, rg_y, <span class="at">method =</span> <span class="st">"pearson"</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>rs_manual</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9057895</code></pre>
</div>
</div>
<p>se observa que al aplicar pearson a los rangos se tiene un valor de <strong>0.906</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>rs_cor <span class="ot">&lt;-</span> <span class="fu">cor</span>(x, y, <span class="at">method =</span> <span class="st">"spearman"</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>rs_cor</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9057895</code></pre>
</div>
</div>
<p>Ahora al aplicarse la función de Spearman directamente, se obtiene el mismo valor <strong>0.906</strong></p>
<p>En presencia de empates, Spearman ajusta los rangos asignando promedios. El valor calculado manualmente coincide exactamente con el obtenido mediante <code>cor(..., method="spearman")</code>, dado que el algoritmo interno también trabaja aplicando Pearson sobre los rangos ajustados.</p>
</section>
</section>
<section id="que-es-una-relación-monotónica-o-tambien-llamado-asociación-monotónica" class="level2">
<h2 class="anchored" data-anchor-id="que-es-una-relación-monotónica-o-tambien-llamado-asociación-monotónica">¿Que es una relación monotónica o tambien llamado asociación monotónica?</h2>
<p>Una función o relación <span class="math inline">f(x)</span> entre <span class="math inline">x</span> e <span class="math inline">y</span> es <strong>monótona</strong> si mantiene <strong>un único sentido</strong> en todo su recorrido: siempre <strong>sube</strong> o siempre <strong>baja</strong>. Puede tener tramos planos, pero <strong>no puede cambiar de dirección</strong>, ademas no exige rectas; solo exige <strong>consistencia en el orden</strong> de los valores.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/fig14.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:20cm"></p>
</figure>
</div>
</div>
</div>
<p>Las relaciones monotónicas describen cómo varía una variable respecto a otra sin requerir linealidad estricta. En una relación monotónica creciente (<span class="math inline">\rho \approx +1</span>), Y aumenta conforme X aumenta, incluso si la forma es lineal, cuadrática o exponencial; Spearman detecta perfectamente esta tendencia. En una relación monotónica decreciente (<span class="math inline">\rho \approx -1</span>), X incrementa mientras Y disminuye de manera consistente, y Spearman identifica claramente esta correlación negativa. Finalmente, en una relación no monotónica (<span class="math inline">\rho \approx 0</span>), la asociación cambia de dirección sube, baja y vuelve a subir, por lo que no existe un orden estable entre X e Y y Spearman indica ausencia de monotonicidad.</p>
<section id="asociación-monótona-spearman-alto-pearson" class="level3">
<h3 class="anchored" data-anchor-id="asociación-monótona-spearman-alto-pearson">Asociación monótona (Spearman ≈ alto, Pearson ↓)</h3>
<p>Se generó un conjunto de datos sintético compuesto por 200 observaciones para dos variables continuas <span class="math inline">x</span> e <span class="math inline">y</span>. Antes de comparar los coeficientes de correlación de Pearson (paramétrico) y Spearman (no paramétrico), es necesario verificar si los supuestos asociados al uso de Pearson se cumplen, especialmente normalidad.</p>
<p>Aunque Spearman también puede aplicarse a variables cuantitativas, sin embargo se debe aplica a este tipo cuando la relación no es lineal pero sí monótona, no se cumple normalidad, o existen valores atípicos,</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># creación de la data</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">999</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">sort</span>(<span class="fu">runif</span>(<span class="dv">200</span>, <span class="dv">1</span>, <span class="dv">100</span>)) <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">200</span>, <span class="dv">0</span>, <span class="dv">2</span>)   </span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> scales<span class="sc">::</span><span class="fu">rescale</span>(x, <span class="at">to =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">100</span>))           <span class="co"># reescala para mantener rango</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>y_true <span class="ot">&lt;-</span> <span class="dv">15</span> <span class="sc">*</span> <span class="fu">log</span>(x)                             <span class="co"># relación monótona no lineal</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> y_true <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">200</span>, <span class="dv">0</span>, <span class="dv">3</span>)                    </span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(x, y)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Aplico el test de normalidad para validar el uso</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nortest)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Test Anderson-Darling</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>ad_x  <span class="ot">&lt;-</span> <span class="fu">ad.test</span>(data<span class="sc">$</span>x)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>ad_y  <span class="ot">&lt;-</span> <span class="fu">ad.test</span>(data<span class="sc">$</span>y)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>ad_x</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Anderson-Darling normality test

data:  data$x
A = 2.4259, p-value = 3.734e-06</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>ad_y</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Anderson-Darling normality test

data:  data$y
A = 5.9481, p-value = 1.112e-14</code></pre>
</div>
</div>
<p>Ambas variables muestran una fuerte desviación de la normalidad según la prueba de Anderson–Darling, por lo que se recomienda usar métodos no paramétricos, como Spearman para correlación.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Correlaciones</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>cor_pearson <span class="ot">&lt;-</span> <span class="fu">cor</span>(data<span class="sc">$</span>x, data<span class="sc">$</span>y, <span class="at">method =</span> <span class="st">"pearson"</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>cor_spearman <span class="ot">&lt;-</span> <span class="fu">cor</span>(data<span class="sc">$</span>x, data<span class="sc">$</span>y, <span class="at">method =</span> <span class="st">"spearman"</span>)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>cor_pearson</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="do">## [1] 0.8867464</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>cor_spearman</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a><span class="do">## [1] 0.9469692</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<ul>
<li>La correlación de Pearson es: <strong>0.887</strong><br>
</li>
<li>La correlación de Spearman es: <strong>0.947</strong></li>
</ul>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggstatsplot)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Gráfico usando Spearman</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>spearman <span class="ot">&lt;-</span> <span class="fu">ggscatterstats</span>(</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data,</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> x,</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> y,</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">"nonparametric"</span>,</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">title =</span> <span class="st">"Spearman"</span>,</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Variable X"</span>,</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Variable Y"</span>,</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">point.args =</span> <span class="fu">list</span>(<span class="at">size =</span> <span class="dv">3</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>),</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">smooth.line.args =</span> <span class="fu">list</span>(<span class="at">method =</span> <span class="st">"loess"</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>),</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">ggplot.component =</span> <span class="fu">list</span>(</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">8</span>))  </span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>pearson <span class="ot">&lt;-</span> <span class="fu">ggscatterstats</span>(</span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data,</span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> x,</span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> y,</span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">"parametric"</span>,</span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">title =</span> <span class="st">"Pearson"</span>,</span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Variable X"</span>,</span>
<span id="cb21-26"><a href="#cb21-26" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Variable Y"</span>,</span>
<span id="cb21-27"><a href="#cb21-27" aria-hidden="true" tabindex="-1"></a>  <span class="at">point.args =</span> <span class="fu">list</span>(<span class="at">size =</span> <span class="dv">3</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>),</span>
<span id="cb21-28"><a href="#cb21-28" aria-hidden="true" tabindex="-1"></a>  <span class="at">smooth.line.args =</span> <span class="fu">list</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>),</span>
<span id="cb21-29"><a href="#cb21-29" aria-hidden="true" tabindex="-1"></a>  <span class="at">ggplot.component =</span> <span class="fu">list</span>(</span>
<span id="cb21-30"><a href="#cb21-30" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">8</span>))   </span>
<span id="cb21-31"><a href="#cb21-31" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb21-32"><a href="#cb21-32" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb21-33"><a href="#cb21-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-34"><a href="#cb21-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-35"><a href="#cb21-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-36"><a href="#cb21-36" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb21-37"><a href="#cb21-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-38"><a href="#cb21-38" aria-hidden="true" tabindex="-1"></a>spearman <span class="sc">+</span> pearson</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/fig15.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:20cm"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Pearson baja porque evalúa linealidad.</p></li>
<li><p>Spearman se mantiene elevada porque evalúa asociación monotómica.</p></li>
<li><p>Este caso demuestra claramente la diferencia conceptual entre ambos coeficientes.</p></li>
</ul>
<blockquote class="blockquote">
<p>Es importante saber que la no normalidad no invalida calcular Pearson, solo afecta la inferencia (p-value, IC).</p>
</blockquote>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Monotonía vs Linealidad
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li><strong>Linealidad</strong> implica que la relación tiene forma de recta:<br>
<span class="math display">
y = a + bx
</span></li>
<li><strong>Monotonía</strong> solo requiere que Y mantenga un orden estable cuando aumenta X.</li>
</ul>
</div>
</div>
</div>
</section>
</section>
<section id="supuestos-del-coeficiente-de-spearman-rho" class="level2">
<h2 class="anchored" data-anchor-id="supuestos-del-coeficiente-de-spearman-rho">Supuestos del coeficiente de Spearman (<span class="math inline">\rho</span>)</h2>
<p>Aunque Spearman es no paramétrico, sí tiene supuestos mínimos. Puedes explicar</p>
<p>l coeficiente de correlación de Spearman (<span class="math inline">\rho</span>) es una medida no paramétrica que evalúa la fuerza y dirección de la relación monótona entre dos variables. Sus supuestos son:</p>
<ol type="1">
<li><p><strong>Variables ordinales, de intervalo o de razón:</strong><br>
Las variables analizadas deben ser al menos ordinales, ya que Spearman se basa en los rangos de los datos.</p></li>
<li><p><strong>Relación monótona:</strong><br>
Se asume que la relación entre las variables es monótona (creciente o decreciente) en la población. No es necesario que sea lineal.</p></li>
<li><p><strong>Ausencia de valores extremos influyentes:</strong><br>
Spearman es menos sensible a outliers que Pearson, pero valores extremadamente atípicos pueden afectar los rangos y la magnitud de <span class="math inline">\rho</span>.</p></li>
<li><p><strong>Muestreo aleatorio:</strong><br>
Los datos deben provenir de una muestra representativa de la población, Spearman asume muestreo aleatorio para que sus propiedades de estimador y el test asociado sean válidos..</p></li>
<li><p><strong>No requiere normalidad ni homocedasticidad:</strong><br>
A diferencia de Pearson, Spearman no asume que las variables sigan distribución normal ni que presenten varianzas homogéneas, por lo que es adecuado para datos con distribuciones sesgadas o heterocedásticas.</p></li>
</ol>
</section>
<section id="interpretación-de-rho-de-spearman" class="level2">
<h2 class="anchored" data-anchor-id="interpretación-de-rho-de-spearman">Interpretación de <span class="math inline">\rho</span> de Spearman</h2>
<p>El coeficiente de correlación de Spearman (<span class="math inline">\rho</span>) mide la <strong>fuerza y dirección de la relación monótona</strong> entre dos variables, utilizando los rangos de los datos.</p>
<section id="rango-de-valores" class="level3">
<h3 class="anchored" data-anchor-id="rango-de-valores">Rango de valores</h3>
<ul>
<li>El valor de <span class="math inline">\rho</span> se encuentra en el intervalo <strong>[-1, +1]</strong>:
<ul>
<li><span class="math inline">\rho = +1</span>: relación <strong>monótona creciente perfecta</strong>, todos los rangos de una variable aumentan cuando los de la otra también aumentan.</li>
<li><span class="math inline">\rho = -1</span>: relación <strong>monótona decreciente perfecta</strong>, los rangos de una variable disminuyen cuando los de la otra aumentan.</li>
<li><span class="math inline">\rho = 0</span>: <strong>ausencia de relación monótona</strong>, los rangos de las variables no presentan un patrón consistente.</li>
</ul></li>
</ul>
</section>
<section id="fuerza-de-la-relación" class="level3">
<h3 class="anchored" data-anchor-id="fuerza-de-la-relación">Fuerza de la relación</h3>
<p>Aunque los límites exactos dependen del contexto y la disciplina, una guía generalmente aceptada es:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Rango de <span class="math inline">\rho</span></th>
<th>Interpretación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>-1.00 a -0.91</td>
<td>Correlación negativa perfecta</td>
</tr>
<tr class="even">
<td>-0.90 a -0.76</td>
<td>Correlación negativa muy fuerte</td>
</tr>
<tr class="odd">
<td>-0.75 a -0.51</td>
<td>Correlación negativa considerable</td>
</tr>
<tr class="even">
<td>-0.50 a -0.11</td>
<td>Correlación negativa media</td>
</tr>
<tr class="odd">
<td>-0.10 a -0.01</td>
<td>Correlación negativa débil</td>
</tr>
<tr class="even">
<td>0.00</td>
<td>No existe correlación</td>
</tr>
<tr class="odd">
<td>+0.01 a +0.10</td>
<td>Correlación positiva débil</td>
</tr>
<tr class="even">
<td>+0.11 a +0.50</td>
<td>Correlación positiva media</td>
</tr>
<tr class="odd">
<td>+0.51 a +0.75</td>
<td>Correlación positiva considerable</td>
</tr>
<tr class="even">
<td>+0.76 a +0.90</td>
<td>Correlación positiva muy fuerte</td>
</tr>
<tr class="odd">
<td>+0.91 a +1.00</td>
<td>Correlación positiva perfecta</td>
</tr>
</tbody>
</table>
<p>Los criterios para interpretar la magnitud de <span class="math inline">\rho</span> no son universales; la tabla se presenta como una guía orientativa, sujeta al contexto de estudio.</p>
</section>
</section>
<section id="ejemplos-practicos-usando-r" class="level2">
<h2 class="anchored" data-anchor-id="ejemplos-practicos-usando-r">Ejemplos practicos usando R</h2>
<p>El coeficiente de Spearman presenta ventajas importantes, ya que:</p>
<ul>
<li><p>NO exige normalidad</p></li>
<li><p>NO exige homocedasticidad</p></li>
<li><p>NO exige linealidad</p></li>
</ul>
<p>Sin embargo, sí es necesario asegurarse de que se cumplen sus criterios conceptuales básicos, entre ellos:</p>
<ul>
<li><p>Que las variables sean ordinales, de intervalo o de razón, lo cual se determina por la naturaleza de las variables y no mediante pruebas estadísticas;</p></li>
<li><p>Que la relación entre las variables sea potencialmente monótona, lo que se evalúa de manera exploratoria mediante gráficos de dispersión.</p></li>
</ul>
<p>Por ello, se utilizará el coeficiente de Spearman, adecuado para datos no normales, presencia de outliers moderados y para analizar relaciones monótonas</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Ejemplo con datos ordinales
</div>
</div>
<div class="callout-body-container callout-body">
<p>Spearman trabaja sobre rangos, por lo tanto las variables ordinales ya son rangos naturales, por consiguiente, Spearman es teóricamente adecuado sin necesidad de tests previos, a continuación tenemos el siguiente caso:</p>
<p>Una empresa que ofrece software de gestión comercial quiere entender mejor el comportamiento de sus clientes. En particular, sospechan que existe una relación entre:</p>
<ul>
<li><p>Satisfacción del cliente (medida en una escala ordinal del 1 al 5), y</p></li>
<li><p>Frecuencia de uso del software (también en escala ordinal del 1 al 5).</p></li>
</ul>
<p>La lógica empresarial detrás de esta hipótesis es simple: <em>Si los clientes están más satisfechos, deberían usar el sistema con mayor frecuencia.</em></p>
<p>La dirección quiere comprobar si esta asociación realmente existe para justificar futuras inversiones en 120 clientes.Sin embargo, antes de tomar decisiones, el equipo de análisis debe verificar estadísticamente si la relación es real o solo una percepción.</p>
</div>
</div>
<p>Presentamos la data con observaciones de respuesta en escala de likert, pero solo mostramos las 10 primera observaciones:</p>
<div class="cell">
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<caption>Primeros 10 registros de satisfacción y frecuencia</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">satisfaccion</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">frecuencia</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>Dado que solo existen 5 niveles (likert), por lógica habrán muchos empates entre las respuestas obtenidas, sin embargo esto sigue siendo valido teóricamente.</p>
<p><strong>Hipótesis estadística</strong></p>
<p>Se plantea la siguiente hipótesis para evaluar la relación entre satisfacción del cliente y frecuencia de uso del software:</p>
<ul>
<li><strong>Hipótesis nula <span class="math inline">H_0</span>:</strong> No existe relación monotónica significativa entre la satisfacción y la frecuencia de uso del software.</li>
<li><strong>Hipótesis alternativa <span class="math inline">H_1</span>:</strong> Existe una relación monotónica significativa entre la satisfacción y la frecuencia de uso del software.</li>
</ul>
<p><strong>Criterio de evaluación</strong> Nivel de significancia: <span class="math inline">\alpha</span> = 0.05</p>
<ul>
<li>Si el p-valor ≤ 0.05, se rechaza <span class="math inline">H_0</span>.</li>
<li>Si el p-valor &gt; 0.05, no se rechaza <span class="math inline">H_0</span>.</li>
</ul>
<p>Para calcular la correlación de Spearman se utilizó la función <code>cor.test()</code> de R, la cual permite estimar tanto el coeficiente de correlación como el p-valor asociado a la prueba de hipótesis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Spearman</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>cor_spearman <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(data<span class="sc">$</span>satisfaccion,</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>                          data<span class="sc">$</span>frecuencia,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>                          <span class="at">method =</span> <span class="st">"spearman"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<caption>Correlación de Spearman entre Satisfacción y Frecuencia</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable 1</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable 2</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">N</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">r_s</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">rho</td>
<td style="text-align: left;">Satisfacción</td>
<td style="text-align: left;">Frecuencia</td>
<td style="text-align: right;">120</td>
<td style="text-align: right;">0.908</td>
<td style="text-align: left;">&lt; .001</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p><strong>INTERPRETACIÓN</strong></p>
<p>El coeficiente de correlación de Spearman obtenido es rho = 0.908, indicando una fuerte relación positiva entre satisfacción y frecuencia de uso del software.</p>
<p>El p-valor asociado es 2.21^{-46}, mucho menor que 0.05, por lo que rechazamos la hipótesis nula.</p>
<p>Esto significa que, estadísticamente, existe evidencia suficiente para afirmar que a mayor satisfacción del cliente, mayor es la frecuencia de uso del software.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Ejemplo con variables compuestas
</div>
</div>
<div class="callout-body-container callout-body">
<p>Se aplicó un cuestionario a un grupo de alumnos para explorar la relación entre <strong>motivación académica</strong> y <strong>desempeño percibido</strong>, dos variables que, según la literatura, están teóricamente relacionadas: a mayor motivación, se espera mayor desempeño.</p>
<p>Cada constructo se midió mediante <strong>6 ítems en escala de Likert</strong> (1 = Muy en desacuerdo, 5 = Muy de acuerdo).</p>
<p>Para cada constructo, se sumaron los 6 ítems individuales para generar <strong>una variable compuesta</strong> que refleje el nivel general del alumno en ese aspecto. Esto es una práctica común en investigación social, ya que <strong>la suma de escalas de Likert captura mejor el constructo global</strong> que un solo ítem y permite análisis estadísticos más robustos.</p>
</div>
</div>
<p>En este caso, la suma de ítems tiende a aproximarse a una distribución normal según el Teorema del Límite Central, especialmente si los ítems son independientes y la muestra es moderada o grande. Por ello, muchos estudios en ciencias sociales, que utilizan cuestionarios con escala Likert, suelen aplicar test de normalidad a las variables compuestas. Sin embargo, existen ciertas opiniones divididas al respecto, dado que estas variables provienen de la suma de puntajes ordinales y presentan un número limitado de categorías, los tests de normalidad pueden resultar sensibles y no necesariamente reflejar el ajuste real.</p>
<p>A continuación tenemos la siguiente data sobre el problema planteado:</p>
<p>Mostramos las 5 primeras filas donde se aprecian los 6 ítems para cada variable y al final la suma de estos, formando asi una variable compuesta</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">mot_1</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mot_2</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mot_3</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mot_4</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mot_5</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mot_6</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">motivacion_total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">20</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">13</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">22</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">18</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">14</td>
</tr>
</tbody>
</table>


</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">des_1</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">des_2</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">des_3</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">des_4</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">des_5</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">des_6</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">desempeno_total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">23</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">13</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">22</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">17</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">14</td>
</tr>
</tbody>
</table>


</div>
</div>
<p><strong>Prueba de hipótesis</strong></p>
<ul>
<li><strong><span class="math inline">H_0</span>:</strong> No existe relación monotónica entre motivación y desempeño académico.<br>
</li>
<li><strong><span class="math inline">H_1</span>:</strong> Existe una relación monotónica entre motivación y desempeño académico.</li>
</ul>
<p><strong>Criterio de evaluación</strong> Nivel de significancia: <span class="math inline">\alpha</span> = 0.05</p>
<ul>
<li>Si el p-valor ≤ 0.05, se rechaza <span class="math inline">H_0</span>.</li>
<li>Si el p-valor &gt; 0.05, no se rechaza <span class="math inline">H_0</span>.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Correlación de Spearman</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>cor_spearman <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(data<span class="sc">$</span>motivacion, data<span class="sc">$</span>desempeno, <span class="at">method =</span> <span class="st">"spearman"</span>, <span class="at">exact =</span> <span class="cn">FALSE</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<caption>Correlación de Spearman entre Motivación y Desempeño</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable 1</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable 2</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">N</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">r_s</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">rho</td>
<td style="text-align: left;">Motivación</td>
<td style="text-align: left;">Desempeño</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">0.915</td>
<td style="text-align: left;">&lt; .001</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>El coeficiente de correlación de Spearman obtenido es rho = 0.915, indicando una fuerte relación positiva entre motivación y desempeño académico.</p>
<p>El p-valor asociado es 1.62^{-40}, mucho menor que 0.05, por lo que rechazamos la hipótesis nula.</p>
<p>Esto significa que, estadísticamente, existe evidencia suficiente para afirmar que a mayor motivación, mayor es el desempeño académico en esta muestra.</p>
<p><strong>Visualización usando la función <code>ggscatterstats()</code> de <code>library(ggstatsplot)</code> en R creado por <span class="citation" data-cites="Patil2021">(<a href="#ref-Patil2021" role="doc-biblioref">Patil, 2021</a>)</span></strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Gráfico usando Spearman</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggscatterstats</span>(</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data,</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> motivacion,</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> desempeno,</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">"nonparametric"</span>,      <span class="co"># Para Spearman</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">title =</span> <span class="st">"Spearman"</span>,</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Variable X"</span>,</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Variable Y"</span>,</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">point.args =</span> <span class="fu">list</span>(<span class="at">size =</span> <span class="dv">3</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>),</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">smooth.line.args =</span> <span class="fu">list</span>(<span class="at">method =</span> <span class="st">"loess"</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>)</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/fig16.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:16cm"></p>
</figure>
</div>
</div>
</div>
<p>Para explorar gráficamente relaciones entre varias variables y complementar el análisis de correlación, se pueden usar funciones como <code>pairs.panels()</code> del paquete <code>psych</code> o <code>ggpairs()</code> del paquete <code>GGally</code>. Ambas permiten generar gráficos de pares de variables de forma rápida y visual, facilitando la interpretación de tendencias y correlaciones en conjuntos de datos con más de dos variables.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
En Resumen
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li><strong>Pearson</strong> → mide <em>asociación lineal</em>.</li>
<li><strong>Spearman</strong> → mide <em>asociación monotónica</em> (aumenta o disminuye de forma consistente, aunque no sea recto).</li>
<li><strong>Spearman usa rangos</strong>, por lo que:
<ul>
<li>No necesita normalidad.</li>
<li>No exige homocedasticidad.</li>
<li>Es robusto ante valores atípicos.</li>
</ul></li>
<li><strong>Variables aplicables</strong>:
<ul>
<li>Ordinales.</li>
<li>Cuantitativas no normales.</li>
<li>Cuantitativas con outliers.</li>
<li>Datos con relación monotónica no lineal.</li>
</ul></li>
<li><strong>Cuando la relación NO es lineal</strong>, Pearson puede fallar.</li>
<li><strong>Pero ojo:</strong> <em>Spearman no detecta cualquier relación no lineal</em>. Solo funciona si la relación es monotónica.<br>
Si la relación cambia de dirección (sube-baja-sube), Spearman puede dar ρ ≈ 0 aunque exista relación.</li>
</ul>
<section id="coeficiente-de-correlación" class="level3">
<h3 class="anchored" data-anchor-id="coeficiente-de-correlación"><strong>Coeficiente de correlación</strong></h3>
<p>El coeficiente de correlación es un estadístico que cuantifica el <strong>grado de asociación</strong> entre dos variables. Sus valores se encuentran en el intervalo <strong>[-1, 1]</strong>, donde:</p>
<ul>
<li><span class="math inline">+1</span> indica correlación positiva perfecta,<br>
</li>
<li><span class="math inline">-1</span> indica correlación negativa perfecta,<br>
</li>
<li><span class="math inline">0</span> indica ausencia de correlación lineal (en Pearson) o de correlación monotónica (en Spearman).</li>
</ul>
</section>
<section id="coeficiente-de-determinación-r²" class="level3">
<h3 class="anchored" data-anchor-id="coeficiente-de-determinación-r²"><strong>Coeficiente de determinación (R²)</strong></h3>
<p>El coeficiente de determinación, denotado como <span class="math inline">R^2</span>, se define como el <strong>cuadrado del coeficiente de correlación</strong>:</p>
<p><span class="math inline">R^2 = r^2</span></p>
<p>En el contexto del coeficiente de Pearson, <span class="math inline">R^2</span> representa la <strong>proporción de la variabilidad de la variable dependiente que es explicada por la variable independiente</strong> bajo un modelo lineal.<br>
Cuando el coeficiente corresponde a Spearman, su cuadrado no tiene interpretación como varianza explicada; solo refleja la fuerza relativa de la asociación monotónica.</p>
</section>
<section id="rho-de-spearman-ρ" class="level3">
<h3 class="anchored" data-anchor-id="rho-de-spearman-ρ"><strong>Rho de Spearman (ρ)</strong></h3>
<p>El coeficiente de correlación de rangos de Spearman se denota por la letra griega <span class="math inline">ρ</span> (rho).<br>
Es un estadístico no paramétrico que evalúa la <strong>fuerza y dirección de la relación monotónica</strong> entre dos variables, trabajando sobre los <strong>rangos</strong> en lugar de los valores originales.</p>
</section>
</div>
</div>
</div>
</section>
<section id="bibliografia-recomendada" class="level2">
<h2 class="anchored" data-anchor-id="bibliografia-recomendada">Bibliografia Recomendada</h2>
<p>1️⃣ Montgomery, D. C., &amp; Runger, G. C. (2021). Applied statistics and probability for engineers (7th ed.). Wiley.</p>
<p>2️⃣ Moore, D. S., McCabe, G. P., &amp; Craig, B. A. (2020). Introduction to the practice of statistics (10th ed.). W.H. Freeman.</p>
<p>3️⃣ Hollander, M., Wolfe, D. A., &amp; Chicken, E. (2014). Nonparametric statistical methods (3rd ed.). Wiley.</p>
<p>4️⃣ Wasserman, L. (2006). All of nonparametric statistics. Springer.</p>
<p>5️⃣ Lehmann, E. L. (2006). Nonparametrics: Statistical methods based on ranks. Springer.</p>
<p>6️⃣ Gibbons, J. D., &amp; Chakraborti, S. (2010). Nonparametric statistical inference (5th ed.). CRC Press.</p>



</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Volver arriba</a><div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">Referencias</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-Patil2021" class="csl-entry" role="listitem">
Patil, I. (2021). Visualizations with statistical details: The ’ggstatsplot’ approach. <em>Journal of Open Source Software</em>, <em>6</em>(61), 3167. <a href="https://doi.org/10.21105/joss.03167">https://doi.org/10.21105/joss.03167</a>
</div>
</div></section><section class="quarto-appendix-contents" id="quarto-citation"><h2 class="anchored quarto-appendix-heading">Cómo citar</h2><div><div class="quarto-appendix-secondary-label">BibTeX</div><pre class="sourceCode code-with-copy quarto-appendix-bibtex"><code class="sourceCode bibtex">@online{ojeda_s.2025,
  author = {Ojeda S., Jairon},
  title = {Coeficiente de Correlación de los Rangos de Spearman},
  date = {2025-09-15},
  url = {https://jaironkevin.github.io/blog/3.html},
  langid = {es}
}
</code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre><div class="quarto-appendix-secondary-label">Por favor, cita este trabajo como:</div><div id="ref-ojeda_s.2025" class="csl-entry quarto-appendix-citeas" role="listitem">
Ojeda S., J. (2025, September 15). <em>Coeficiente de Correlación de los
Rangos de Spearman</em>. <a href="https://jaironkevin.github.io/blog/3.html">https://jaironkevin.github.io/blog/3.html</a>
</div></div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/jaironkevin\.github\.io\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2025 Jairon Ojeda. Website built with Quarto in RStudio</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/jaironkevin">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="../www.linkedin.com/in/jairon-ojeda">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>