---
author: Jairon K. Ojeda S., Jahayra S. Rodriguez R.
date: 2024-07-31
title: "Modelo SARIMA y red neuronal recurrente para el pronóstico de la producción de mango en el valle de San Lorenzo, 2024-2026"
details: Tesis, Universidad Nacional de Piura
link: https://github.com/jaironkevin/SARIMA_LSTM/blob/main/Tesis.pdf # ejemplo: pdf subido a GitHub
github: jaironkevin/SARIMA_LSTM
orcid: 0009-0003-8484-8681
lang: es
---

# RESUMEN

El presente estudio, titulado “Modelo SARIMA y red neuronal recurrente para el pronóstico de la producción de mango en el valle de San Lorenzo, 2024-2026”, tuvo como objetivo general determinar la eficiencia de los modelos SARIMA y redes neuronales LSTM en el pronóstico mensual de la producción de mango. La investigación adoptó un enfoque cuantitativo, con diseño no experimental, de tipo aplicada y nivel predictivo, por otro lado la población comprendió todos los meses con registros de producción desde el inicio de la actividad hasta la actualidad, extrayéndose como muestra el periodo comprendido entre enero de 2000 y agosto de 2024. La información fue obtenida mediante búsqueda electrónica, solicitada a MIDAGRI y descargada en hojas de cálculo de Excel. En el análisis descriptivo, la serie de producción mensual de mango mostró alta variabilidad, con presencia de valores extremos que elevaron la media (15,148 t) frente a una mediana considerablemente menor (235 t), lo que evidencia una distribución sesgada. Se identificó una clara estacionalidad, con picos en diciembre y enero, y baja producción entre abril y julio debido a las temporadas. Siguiendo la metodología Box-Jenkins, se evaluaron siete modelos SARIMA, destacando el modelo SARIMA(1,0,0)(2,1,0)[12] como el más eficiente (MAE = 8,217; MASE = 0.833). Paralelamente, se entrenaron 4 modelos LSTM utilizando Keras3, destacando el modelo A con una arquitectura de dos capas ocultas (256 y 128 unidades), 24 entradas y 17 salidas. Posteriormente al comparar ambos modelos sobre un conjunto de prueba de 21 meses, el modelo SARIMA presentó un mejor desempeño en métricas clave (MAE y RMSE), especialmente en la predicción de valores extremos. Se concluye que el modelo SARIMA(1,0,0)(2,1,0)[12] es el más eficiente para ajustar y predecir la serie de tiempo de producción de mango en el valle de San Lorenzo. La proyección muestra un crecimiento progresivo desde agosto (1,472.69 t) hasta noviembre (10,520.33 t), seguido de una ligera caída en diciembre (8,214.21 t) y un repunte estimado en enero de 2026 (9,547.92 t).




